name: Expo OTA Update

on:
  push:
    branches: [ preview, main ] # می‌توانید branchهای مورد نظر را اضافه کنید

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # استفاده از نسخه LTS
          cache: 'npm'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci # استفاده از npm ci برای نصب سریع‌تر و قابل اطمینان‌تر

      - name: Publish OTA Update
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas update --branch ${{ github.ref_name }} --message "OTA Update: ${{ github.event.head_commit.message || 'Automated update' }}"