name: Expo OTA Update

on:
  push:
    branches: [preview, develop]

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Create CI polyfills
        run: |
          mkdir -p scripts
          cat > scripts/ci-polyfills.js << 'EOF'
          if (typeof window === 'undefined') {
            global.window = {};
            global.document = {};
            global.navigator = {};
            global.localStorage = {
              getItem: () => null,
              setItem: () => {},
              removeItem: () => {},
            };
          }
          EOF

      - name: Publish OTA Update
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          CI: "true"
          NODE_OPTIONS: "--require ./scripts/ci-polyfills.js"
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          eas update --branch $BRANCH_NAME --message "آپدیت: ${{ github.event.head_commit.message || 'Auto-update' }}"